[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "2.7.2"

[context.production]
  command = "bundle install && bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle install && bundle exec jekyll build --future"

[context.branch-deploy]
  command = "bundle install && bundle exec jekyll build"
