[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

# Let Netlify use its default pre-installed Ruby version
# [build.environment]
#   RUBY_VERSION = "3.0.6"

[context.production]
  command = "bundle install && bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle install && bundle exec jekyll build --future"

[context.branch-deploy]
  command = "bundle install && bundle exec jekyll build"
